CREATE TABLE admins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  hash TEXT,
  role TEXT,
  created TEXT,
  last_login TEXT,
  active INTEGER DEFAULT 1
);
CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY,
  admin_id INTEGER REFERENCES admins(id),
  expires BIGINT
);
CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  active INTEGER DEFAULT 1
);
CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE,
  description TEXT,
  category TEXT,
  product_type TEXT NOT NULL DEFAULT 'GOODS',
  price INTEGER NOT NULL CHECK(price > 0),
  discount INTEGER DEFAULT 0 CHECK(discount >= 0),
  stock INTEGER NOT NULL CHECK(stock >= 0),
  active INTEGER DEFAULT 1,
  image TEXT,
  created TEXT,
  updated TEXT,
  carton_price INTEGER,
  carton_qty INTEGER,
  size TEXT,
  image_front TEXT,
  image_back TEXT,
  colors TEXT,
  quality TEXT,
  video_url TEXT,
  featured INTEGER DEFAULT 0,
  category_id INTEGER REFERENCES categories(id),
  style TEXT,
  best_seller INTEGER NOT NULL DEFAULT 0,
  new_arrival INTEGER NOT NULL DEFAULT 0,
  flash_deal INTEGER NOT NULL DEFAULT 0,
  low_stock INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX ix_prod ON products(category, active);
CREATE INDEX ix_pcat ON products(category_id);
CREATE TABLE customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone TEXT UNIQUE,
  email TEXT,
  created TEXT
);
CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no TEXT UNIQUE,
  customer_id INTEGER REFERENCES customers(id),
  address TEXT,
  state TEXT,
  city TEXT,
  notes TEXT,
  gps TEXT,
  subtotal INTEGER,
  fee INTEGER,
  total INTEGER,
  pay_status TEXT DEFAULT 'pending',
  status TEXT DEFAULT 'payment_pending',
  stocked INTEGER DEFAULT 0,
  created TEXT,
  updated TEXT,
  discount INTEGER NOT NULL DEFAULT 0,
  coupon_code TEXT,
  idem TEXT,
  delivery_option TEXT NOT NULL DEFAULT 'standard'
);
CREATE INDEX ix_ord ON orders(pay_status, status, customer_id);
CREATE UNIQUE INDEX ux_idem ON orders(idem);
CREATE TABLE order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id),
  product_id INTEGER,
  name TEXT,
  qty INTEGER,
  price INTEGER,
  pack TEXT DEFAULT 'unit',
  pack_qty INTEGER DEFAULT 1,
  variant TEXT NOT NULL DEFAULT '{}'
);
CREATE TABLE payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id),
  provider TEXT,
  reference TEXT UNIQUE,
  amount INTEGER,
  currency TEXT,
  status TEXT,
  response TEXT,
  created TEXT,
  verified TEXT
);
CREATE TABLE settings (k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE order_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id),
  label TEXT,
  at TEXT
);
CREATE TABLE annual_award_winners (
  year INTEGER NOT NULL,
  rank INTEGER NOT NULL,
  customer_id INTEGER,
  name TEXT NOT NULL,
  spend INTEGER NOT NULL,
  paid_orders INTEGER NOT NULL,
  PRIMARY KEY(year, rank)
);
CREATE TABLE annual_award_config (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  reward TEXT NOT NULL DEFAULT ''
);
INSERT INTO annual_award_config(id, reward) VALUES(1, '');
CREATE TABLE coupons (
  code TEXT PRIMARY KEY,
  percent INTEGER NOT NULL CHECK(percent BETWEEN 1 AND 75),
  active INTEGER NOT NULL DEFAULT 1,
  created TEXT NOT NULL
);
CREATE TABLE videos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  staff_id INTEGER REFERENCES admins(id),
  active INTEGER DEFAULT 1,
  created TEXT,
  updated TEXT
);
CREATE INDEX ix_videos ON videos(active, created);
