ALTER TABLE products ADD COLUMN IF NOT EXISTS style TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS best_seller INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS new_arrival INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_deal INTEGER NOT NULL DEFAULT 0;
