const {spawn}=require('child_process'),crypto=require('crypto'),{DatabaseSync}=require('node:sqlite');
const fs=require('fs');try{fs.unlinkSync('/tmp/t.db')}catch{}
const env={...process.env,PORT:'3999',DB_PATH:'/tmp/t.db',ADMIN_EMAIL:'o@x.com',ADMIN_PASSWORD:'correct-horse-battery',PAYSTACK_SECRET_KEY:'sk_test_dummy',PUBLIC_URL:'http://x'};
const s=spawn('node',['server.js'],{env,stdio:'ignore'});let ck='',f=0;
const B='http://localhost:3999/api',H={'content-type':'application/json','x-requested-with':'store'};
const C=async(m,p,b,h={})=>{const r=await fetch(B+p,{method:m,headers:{...H,cookie:ck,...h},body:b&&(typeof b=='string'?b:JSON.stringify(b))});const j=await r.json();if(r.headers.get('set-cookie'))ck=r.headers.get('set-cookie').split(';')[0];return[r.status,j]};
const t=(n,ok)=>{console.log(ok?'PASS':'FAIL',n);if(!ok)f++};
(async()=>{await new Promise(r=>setTimeout(r,800));
 t('admin api blocked when logged out',(await C('GET','/admin/orders'))[0]==401);
 t('bad login rejected',(await C('POST','/admin/login',{email:'o@x.com',password:'nope'}))[0]==401);
 const [,setup]=await C('GET','/admin/setup-status');
 t('owner setup disabled when an admin exists',setup.ownerSetupAvailable===false);
 t('public owner creation rejected after setup',(await C('POST','/admin/create-owner',{name:'Another Owner',email:'new@x.com',password:'another-secure-password',confirmPassword:'another-secure-password'}))[0]==409);
 t('good login ignores email case and surrounding whitespace',(await C('POST','/admin/login',{email:' O@X.COM ',password:'correct-horse-battery'}))[0]==200);
 t('CSRF header required',(await C('POST','/admin/products',{name:'x'},{'x-requested-with':''}))[0]==403);
 t('negative price rejected',(await C('POST','/admin/products',{name:'Shoe',price:-5,stock:3}))[0]==400);
 t('bad image rejected',(await C('POST','/admin/products',{name:'Shoe',price:100,stock:3,image:'data:text/html;base64,AAAA'}))[0]==400);
 const [,pr]=await C('POST','/admin/products',{name:'Sneakers',sku:'SN1',price:10000,discount:8000,stock:2,category:'Shoes'});
 t('product created',pr.id>0);
 const dup=await C('POST','/admin/products',{name:'Yy',sku:'SN1',price:5,stock:1});t('duplicate SKU rejected',dup[0]==409);
 const cust={name:'Ada Obi',phone:'08012345678'},ad={address:'12 Main St',state:'Lagos',city:'Ikeja'};
 t('bad phone rejected',(await C('POST','/orders',{customer:{name:'Ada Obi',phone:'123'},...ad,items:[{id:pr.id,qty:1}]}))[0]==400);
 t('oversell blocked at order',(await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:3}]}))[0]==409);
 const [,o]=await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:2}],total:1});
 t('server computes total (ignores client)',o.total==8000*2+2000);
 const [,o2]=await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:2}]});
 t('order unpaid initially',(await C('POST','/track',{no:o.no,phone:'08012345678'}))[1].pay_status=='pending');
 t('track wrong phone hidden',(await C('POST','/track',{no:o.no,phone:'08099999999'}))[0]==404);
 t('webhook bad signature rejected',(await C('POST','/webhook/paystack','{"event":"charge.success"}',{'x-paystack-signature':'abc'}))[0]==401);
 await C('POST',`/orders/${o.no}/pay`,{}); // offline: provider unreachable, but pending payment row is recorded
 const db=new DatabaseSync('/tmp/t.db');const ref=db.prepare('SELECT reference r FROM payments').get().r;
 const hook=async(d)=>{const raw=JSON.stringify({event:'charge.success',data:d});return C('POST','/webhook/paystack',raw,{'x-paystack-signature':crypto.createHmac('sha512','sk_test_dummy').update(raw).digest('hex')})};
 await hook({reference:ref,status:'success',amount:100,currency:'NGN'});
 t('wrong amount NOT marked paid',(await C('POST','/track',{no:o.no,phone:'08012345678'}))[1].pay_status=='pending');
 await hook({reference:ref,status:'success',amount:o.total*100,currency:'NGN'});
 const tr=(await C('POST','/track',{no:o.no,phone:'08012345678'}))[1];
 t('verified webhook marks paid',tr.pay_status=='paid'&&tr.status=='paid');
 await hook({reference:ref,status:'success',amount:o.total*100,currency:'NGN'});
 t('replay is idempotent, stock deducted once',db.prepare('SELECT stock s FROM products').get().s==0);
 t('admin cannot mark paid manually',(await C('PATCH',`/admin/orders/${o.no}`,{status:'paid'}))[0]==409);
 t('valid transition works',(await C('PATCH',`/admin/orders/${o.no}`,{status:'processing'}))[0]==200);
 t('cancel paid order restores stock',(await C('PATCH',`/admin/orders/${o.no}`,{status:'cancelled'}))[0]==200&&db.prepare('SELECT stock s FROM products').get().s==2);
 const [,d]=await C('GET','/admin/dashboard');t('dashboard real numbers',d.customers==1&&d.cancelled==1);
 t('customers/payments lists',(await C('GET','/admin/customers'))[1].items[0].orders==2&&(await C('GET','/admin/payments'))[1].items.length==1);
 t('public product search',(await C('GET','/products?q=SN1'))[1].total==1);

 const k='idem-1',a1=await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:1}]},{'idempotency-key':k}),a2=await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:1}]},{'idempotency-key':k});
 t('same idempotency key returns same order (no duplicate)',a1[1].no&&a1[1].no==a2[1].no);
 t('settings: owner updates delivery fee',(await C('PUT','/admin/settings',{fee:'3500',name:'Test Shop'}))[1].fee=='3500');
 const [,publicSettings]=await C('GET','/settings');
 t('public settings reflect change',publicSettings.name=='Test Shop');
 t('public settings contain the correct care and delivery contacts',publicSettings.phone=='08127718573'&&publicSettings.wa=='2348127718573'&&publicSettings.care1=='08127718573'&&publicSettings.care2=='07046918331'&&publicSettings.delivery1=='07048243053'&&publicSettings.delivery2=='08139719308');
 const storefront=fs.readFileSync('public/index.html','utf8');
 t('storefront shows responsive tap-to-call contacts and WhatsApp uses Customer Care',storefront.includes('href="tel:${esc(CFG.care1)}"')&&storefront.includes('href="tel:${esc(CFG.care2)}"')&&storefront.includes('href="tel:${esc(CFG.delivery1)}"')&&storefront.includes('href="tel:${esc(CFG.delivery2)}"')&&storefront.includes('https://wa.me/${String(CFG.care1)')&&storefront.includes('grid-template-columns:repeat(auto-fit'));
 const a3=await C('POST','/orders',{customer:cust,...ad,items:[{id:pr.id,qty:1}]});t('new order uses saved delivery fee',a3[1].total==8000+3500);
 const lg=await fetch(B+'/admin/login',{method:'POST',headers:H,body:JSON.stringify({email:'o@x.com',password:'correct-horse-battery'})});t('login response leaks no hash/password',!/hash|password|scrypt/i.test(await lg.text()));
 db.prepare("INSERT INTO admins(name,email,hash,role,created) VALUES('Sam','s@x.com',?, 'staff',?)").run((()=>{const sl=crypto.randomBytes(16);return sl.toString('hex')+':'+crypto.scryptSync('staff-password-1',sl,64).toString('hex')})(),'now');
 ck='';await C('POST','/admin/login',{email:'s@x.com',password:'staff-password-1'});
 t('staff cannot create products',(await C('POST','/admin/products',{name:'Nope',price:5,stock:1}))[0]==403);
 t('staff cannot change settings',(await C('PUT','/admin/settings',{fee:'1'}))[0]==403);
 t('staff can update order status',(await C('PATCH',`/admin/orders/${a3[1].no}`,{status:'cancelled'}))[0]==200);
 ck='sid=deadbeef';t('invalid session rejected',(await C('GET','/admin/orders'))[0]==401);
 ck='';t('anonymous cannot read customers/payments',(await C('GET','/admin/customers'))[0]==401&&(await C('GET','/admin/payments'))[0]==401);
 ck='';await C('POST','/admin/login',{email:'o@x.com',password:'correct-horse-battery'});
 await C('PUT',`/admin/products/${pr.id}`,{name:'Sneakers',sku:'SN1',price:10000,stock:2,active:false});
 t('hidden product not visible to customers',(await C('GET','/products/'+pr.id))[0]==404&&(await C('GET','/products'))[1].total==0);
 console.log(f?f+' FAILED':'ALL PASSED');s.kill();process.exit(f?1:0)})();
